// Generated code. DO NOT EDIT

public enum AllTerrain: Int, CaseIterable, Codable {
	case GrassCenter = 1
	case GrassTop = 2
	case GrassBottom = 3
	case GrassTopBottom = 4
	case GrassLeft = 5
	case GrassTopLeft = 6
	case GrassBottomLeft = 7
	case GrassTopBottomLeft = 8
	case GrassRight = 9
	case GrassTopRight = 10
	case GrassBottomRight = 11
	case GrassTopBottomRight = 12
	case GrassLeftRight = 13
	case GrassTopLeftRight = 14
	case GrassBottomLeftRight = 15
	case GrassTopBottomLeftRight = 16
	case GrassCnrTopLeft = 17
	case GrassBottomCnrTopLeft = 19
	case GrassRightCnrTopLeft = 25
	case GrassBottomRightCnrTopLeft = 27
	case GrassCnrTopRight = 33
	case GrassBottomCnrTopRight = 35
	case GrassLeftCnrTopRight = 37
	case GrassBottomLeftCnrTopRight = 39
	case GrassCnrTopLeftCnrTopRight = 49
	case GrassBottomCnrTopLeftCnrTopRight = 51
	case GrassCnrBottomLeft = 65
	case GrassTopCnrBottomLeft = 66
	case GrassRightCnrBottomLeft = 73
	case GrassTopRightCnrBottomLeft = 74
	case GrassCnrTopLeftCnrBottomLeft = 81
	case GrassRightCnrTopLeftCnrBottomLeft = 89
	case GrassCnrTopRightCnrBottomLeft = 97
	case GrassCnrTopLeftCnrTopRightCnrBottomLeft = 113
	case GrassCnrBottomRight = 129
	case GrassTopCnrBottomRight = 130
	case GrassLeftCnrBottomRight = 133
	case GrassTopLeftCnrBottomRight = 134
	case GrassCnrTopLeftCnrBottomRight = 145
	case GrassCnrTopRightCnrBottomRight = 161
	case GrassLeftCnrTopRightCnrBottomRight = 165
	case GrassCnrTopLeftCnrTopRightCnrBottomRight = 177
	case GrassCnrBottomLeftCnrBottomRight = 193
	case GrassTopCnrBottomLeftCnrBottomRight = 194
	case GrassCnrTopLeftCnrBottomLeftCnrBottomRight = 209
	case GrassCnrTopRightCnrBottomLeftCnrBottomRight = 225
	case GrassCnrTopLeftCnrTopRightCnrBottomLeftCnrBottomRight = 241
	case SandCenter = 242
	case SandTop = 243
	case SandBottom = 244
	case SandTopBottom = 245
	case SandLeft = 246
	case SandTopLeft = 247
	case SandBottomLeft = 248
	case SandTopBottomLeft = 249
	case SandRight = 250
	case SandTopRight = 251
	case SandBottomRight = 252
	case SandTopBottomRight = 253
	case SandLeftRight = 254
	case SandTopLeftRight = 255
	case SandBottomLeftRight = 256
	case SandTopBottomLeftRight = 257
	case SandCnrTopLeft = 258
	case SandBottomCnrTopLeft = 260
	case SandRightCnrTopLeft = 266
	case SandBottomRightCnrTopLeft = 268
	case SandCnrTopRight = 274
	case SandBottomCnrTopRight = 276
	case SandLeftCnrTopRight = 278
	case SandBottomLeftCnrTopRight = 280
	case SandCnrTopLeftCnrTopRight = 290
	case SandBottomCnrTopLeftCnrTopRight = 292
	case SandCnrBottomLeft = 306
	case SandTopCnrBottomLeft = 307
	case SandRightCnrBottomLeft = 314
	case SandTopRightCnrBottomLeft = 315
	case SandCnrTopLeftCnrBottomLeft = 322
	case SandRightCnrTopLeftCnrBottomLeft = 330
	case SandCnrTopRightCnrBottomLeft = 338
	case SandCnrTopLeftCnrTopRightCnrBottomLeft = 354
	case SandCnrBottomRight = 370
	case SandTopCnrBottomRight = 371
	case SandLeftCnrBottomRight = 374
	case SandTopLeftCnrBottomRight = 375
	case SandCnrTopLeftCnrBottomRight = 386
	case SandCnrTopRightCnrBottomRight = 402
	case SandLeftCnrTopRightCnrBottomRight = 406
	case SandCnrTopLeftCnrTopRightCnrBottomRight = 418
	case SandCnrBottomLeftCnrBottomRight = 434
	case SandTopCnrBottomLeftCnrBottomRight = 435
	case SandCnrTopLeftCnrBottomLeftCnrBottomRight = 450
	case SandCnrTopRightCnrBottomLeftCnrBottomRight = 466
	case SandCnrTopLeftCnrTopRightCnrBottomLeftCnrBottomRight = 482

public var filename: String {
	switch self {
		case .GrassCenter: return "Grass_Center"
		case .GrassTop: return "Grass_Top"
		case .GrassBottom: return "Grass_Bottom"
		case .GrassTopBottom: return "Grass_Top_Bottom"
		case .GrassLeft: return "Grass_Left"
		case .GrassTopLeft: return "Grass_Top_Left"
		case .GrassBottomLeft: return "Grass_Bottom_Left"
		case .GrassTopBottomLeft: return "Grass_Top_Bottom_Left"
		case .GrassRight: return "Grass_Right"
		case .GrassTopRight: return "Grass_Top_Right"
		case .GrassBottomRight: return "Grass_Bottom_Right"
		case .GrassTopBottomRight: return "Grass_Top_Bottom_Right"
		case .GrassLeftRight: return "Grass_Left_Right"
		case .GrassTopLeftRight: return "Grass_Top_Left_Right"
		case .GrassBottomLeftRight: return "Grass_Bottom_Left_Right"
		case .GrassTopBottomLeftRight: return "Grass_Top_Bottom_Left_Right"
		case .GrassCnrTopLeft: return "Grass_CnrTopLeft"
		case .GrassBottomCnrTopLeft: return "Grass_Bottom_CnrTopLeft"
		case .GrassRightCnrTopLeft: return "Grass_Right_CnrTopLeft"
		case .GrassBottomRightCnrTopLeft: return "Grass_Bottom_Right_CnrTopLeft"
		case .GrassCnrTopRight: return "Grass_CnrTopRight"
		case .GrassBottomCnrTopRight: return "Grass_Bottom_CnrTopRight"
		case .GrassLeftCnrTopRight: return "Grass_Left_CnrTopRight"
		case .GrassBottomLeftCnrTopRight: return "Grass_Bottom_Left_CnrTopRight"
		case .GrassCnrTopLeftCnrTopRight: return "Grass_CnrTopLeft_CnrTopRight"
		case .GrassBottomCnrTopLeftCnrTopRight: return "Grass_Bottom_CnrTopLeft_CnrTopRight"
		case .GrassCnrBottomLeft: return "Grass_CnrBottomLeft"
		case .GrassTopCnrBottomLeft: return "Grass_Top_CnrBottomLeft"
		case .GrassRightCnrBottomLeft: return "Grass_Right_CnrBottomLeft"
		case .GrassTopRightCnrBottomLeft: return "Grass_Top_Right_CnrBottomLeft"
		case .GrassCnrTopLeftCnrBottomLeft: return "Grass_CnrTopLeft_CnrBottomLeft"
		case .GrassRightCnrTopLeftCnrBottomLeft: return "Grass_Right_CnrTopLeft_CnrBottomLeft"
		case .GrassCnrTopRightCnrBottomLeft: return "Grass_CnrTopRight_CnrBottomLeft"
		case .GrassCnrTopLeftCnrTopRightCnrBottomLeft: return "Grass_CnrTopLeft_CnrTopRight_CnrBottomLeft"
		case .GrassCnrBottomRight: return "Grass_CnrBottomRight"
		case .GrassTopCnrBottomRight: return "Grass_Top_CnrBottomRight"
		case .GrassLeftCnrBottomRight: return "Grass_Left_CnrBottomRight"
		case .GrassTopLeftCnrBottomRight: return "Grass_Top_Left_CnrBottomRight"
		case .GrassCnrTopLeftCnrBottomRight: return "Grass_CnrTopLeft_CnrBottomRight"
		case .GrassCnrTopRightCnrBottomRight: return "Grass_CnrTopRight_CnrBottomRight"
		case .GrassLeftCnrTopRightCnrBottomRight: return "Grass_Left_CnrTopRight_CnrBottomRight"
		case .GrassCnrTopLeftCnrTopRightCnrBottomRight: return "Grass_CnrTopLeft_CnrTopRight_CnrBottomRight"
		case .GrassCnrBottomLeftCnrBottomRight: return "Grass_CnrBottomLeft_CnrBottomRight"
		case .GrassTopCnrBottomLeftCnrBottomRight: return "Grass_Top_CnrBottomLeft_CnrBottomRight"
		case .GrassCnrTopLeftCnrBottomLeftCnrBottomRight: return "Grass_CnrTopLeft_CnrBottomLeft_CnrBottomRight"
		case .GrassCnrTopRightCnrBottomLeftCnrBottomRight: return "Grass_CnrTopRight_CnrBottomLeft_CnrBottomRight"
		case .GrassCnrTopLeftCnrTopRightCnrBottomLeftCnrBottomRight: return "Grass_CnrTopLeft_CnrTopRight_CnrBottomLeft_CnrBottomRight"
		case .SandCenter: return "Sand_Center"
		case .SandTop: return "Sand_Top"
		case .SandBottom: return "Sand_Bottom"
		case .SandTopBottom: return "Sand_Top_Bottom"
		case .SandLeft: return "Sand_Left"
		case .SandTopLeft: return "Sand_Top_Left"
		case .SandBottomLeft: return "Sand_Bottom_Left"
		case .SandTopBottomLeft: return "Sand_Top_Bottom_Left"
		case .SandRight: return "Sand_Right"
		case .SandTopRight: return "Sand_Top_Right"
		case .SandBottomRight: return "Sand_Bottom_Right"
		case .SandTopBottomRight: return "Sand_Top_Bottom_Right"
		case .SandLeftRight: return "Sand_Left_Right"
		case .SandTopLeftRight: return "Sand_Top_Left_Right"
		case .SandBottomLeftRight: return "Sand_Bottom_Left_Right"
		case .SandTopBottomLeftRight: return "Sand_Top_Bottom_Left_Right"
		case .SandCnrTopLeft: return "Sand_CnrTopLeft"
		case .SandBottomCnrTopLeft: return "Sand_Bottom_CnrTopLeft"
		case .SandRightCnrTopLeft: return "Sand_Right_CnrTopLeft"
		case .SandBottomRightCnrTopLeft: return "Sand_Bottom_Right_CnrTopLeft"
		case .SandCnrTopRight: return "Sand_CnrTopRight"
		case .SandBottomCnrTopRight: return "Sand_Bottom_CnrTopRight"
		case .SandLeftCnrTopRight: return "Sand_Left_CnrTopRight"
		case .SandBottomLeftCnrTopRight: return "Sand_Bottom_Left_CnrTopRight"
		case .SandCnrTopLeftCnrTopRight: return "Sand_CnrTopLeft_CnrTopRight"
		case .SandBottomCnrTopLeftCnrTopRight: return "Sand_Bottom_CnrTopLeft_CnrTopRight"
		case .SandCnrBottomLeft: return "Sand_CnrBottomLeft"
		case .SandTopCnrBottomLeft: return "Sand_Top_CnrBottomLeft"
		case .SandRightCnrBottomLeft: return "Sand_Right_CnrBottomLeft"
		case .SandTopRightCnrBottomLeft: return "Sand_Top_Right_CnrBottomLeft"
		case .SandCnrTopLeftCnrBottomLeft: return "Sand_CnrTopLeft_CnrBottomLeft"
		case .SandRightCnrTopLeftCnrBottomLeft: return "Sand_Right_CnrTopLeft_CnrBottomLeft"
		case .SandCnrTopRightCnrBottomLeft: return "Sand_CnrTopRight_CnrBottomLeft"
		case .SandCnrTopLeftCnrTopRightCnrBottomLeft: return "Sand_CnrTopLeft_CnrTopRight_CnrBottomLeft"
		case .SandCnrBottomRight: return "Sand_CnrBottomRight"
		case .SandTopCnrBottomRight: return "Sand_Top_CnrBottomRight"
		case .SandLeftCnrBottomRight: return "Sand_Left_CnrBottomRight"
		case .SandTopLeftCnrBottomRight: return "Sand_Top_Left_CnrBottomRight"
		case .SandCnrTopLeftCnrBottomRight: return "Sand_CnrTopLeft_CnrBottomRight"
		case .SandCnrTopRightCnrBottomRight: return "Sand_CnrTopRight_CnrBottomRight"
		case .SandLeftCnrTopRightCnrBottomRight: return "Sand_Left_CnrTopRight_CnrBottomRight"
		case .SandCnrTopLeftCnrTopRightCnrBottomRight: return "Sand_CnrTopLeft_CnrTopRight_CnrBottomRight"
		case .SandCnrBottomLeftCnrBottomRight: return "Sand_CnrBottomLeft_CnrBottomRight"
		case .SandTopCnrBottomLeftCnrBottomRight: return "Sand_Top_CnrBottomLeft_CnrBottomRight"
		case .SandCnrTopLeftCnrBottomLeftCnrBottomRight: return "Sand_CnrTopLeft_CnrBottomLeft_CnrBottomRight"
		case .SandCnrTopRightCnrBottomLeftCnrBottomRight: return "Sand_CnrTopRight_CnrBottomLeft_CnrBottomRight"
		case .SandCnrTopLeftCnrTopRightCnrBottomLeftCnrBottomRight: return "Sand_CnrTopLeft_CnrTopRight_CnrBottomLeft_CnrBottomRight"
	}
}

}