// Generated code. DO NOT EDIT

public enum OverlayTerrain: Int, CaseIterable, Codable, TileSetEnum {
	case GrassTop = 1
	case GrassBottom = 2
	case GrassTopBottom = 3
	case GrassLeft = 4
	case GrassTopLeft = 5
	case GrassBottomLeft = 6
	case GrassTopBottomLeft = 7
	case GrassRight = 8
	case GrassTopRight = 9
	case GrassBottomRight = 10
	case GrassTopBottomRight = 11
	case GrassLeftRight = 12
	case GrassTopLeftRight = 13
	case GrassBottomLeftRight = 14
	case GrassTopBottomLeftRight = 15
	case GrassCnrTopLeft = 16
	case GrassBottomCnrTopLeft = 18
	case GrassRightCnrTopLeft = 24
	case GrassBottomRightCnrTopLeft = 26
	case GrassCnrTopRight = 32
	case GrassBottomCnrTopRight = 34
	case GrassLeftCnrTopRight = 36
	case GrassBottomLeftCnrTopRight = 38
	case GrassCnrTopLeftCnrTopRight = 48
	case GrassBottomCnrTopLeftCnrTopRight = 50
	case GrassCnrBottomLeft = 64
	case GrassTopCnrBottomLeft = 65
	case GrassRightCnrBottomLeft = 72
	case GrassTopRightCnrBottomLeft = 73
	case GrassCnrTopLeftCnrBottomLeft = 80
	case GrassRightCnrTopLeftCnrBottomLeft = 88
	case GrassCnrTopRightCnrBottomLeft = 96
	case GrassCnrTopLeftCnrTopRightCnrBottomLeft = 112
	case GrassCnrBottomRight = 128
	case GrassTopCnrBottomRight = 129
	case GrassLeftCnrBottomRight = 132
	case GrassTopLeftCnrBottomRight = 133
	case GrassCnrTopLeftCnrBottomRight = 144
	case GrassCnrTopRightCnrBottomRight = 160
	case GrassLeftCnrTopRightCnrBottomRight = 164
	case GrassCnrTopLeftCnrTopRightCnrBottomRight = 176
	case GrassCnrBottomLeftCnrBottomRight = 192
	case GrassTopCnrBottomLeftCnrBottomRight = 193
	case GrassCnrTopLeftCnrBottomLeftCnrBottomRight = 208
	case GrassCnrTopRightCnrBottomLeftCnrBottomRight = 224
	case GrassCnrTopLeftCnrTopRightCnrBottomLeftCnrBottomRight = 240
	case SandTop = 241
	case SandBottom = 242
	case SandTopBottom = 243
	case SandLeft = 244
	case SandTopLeft = 245
	case SandBottomLeft = 246
	case SandTopBottomLeft = 247
	case SandRight = 248
	case SandTopRight = 249
	case SandBottomRight = 250
	case SandTopBottomRight = 251
	case SandLeftRight = 252
	case SandTopLeftRight = 253
	case SandBottomLeftRight = 254
	case SandTopBottomLeftRight = 255
	case SandCnrTopLeft = 256
	case SandBottomCnrTopLeft = 258
	case SandRightCnrTopLeft = 264
	case SandBottomRightCnrTopLeft = 266
	case SandCnrTopRight = 272
	case SandBottomCnrTopRight = 274
	case SandLeftCnrTopRight = 276
	case SandBottomLeftCnrTopRight = 278
	case SandCnrTopLeftCnrTopRight = 288
	case SandBottomCnrTopLeftCnrTopRight = 290
	case SandCnrBottomLeft = 304
	case SandTopCnrBottomLeft = 305
	case SandRightCnrBottomLeft = 312
	case SandTopRightCnrBottomLeft = 313
	case SandCnrTopLeftCnrBottomLeft = 320
	case SandRightCnrTopLeftCnrBottomLeft = 328
	case SandCnrTopRightCnrBottomLeft = 336
	case SandCnrTopLeftCnrTopRightCnrBottomLeft = 352
	case SandCnrBottomRight = 368
	case SandTopCnrBottomRight = 369
	case SandLeftCnrBottomRight = 372
	case SandTopLeftCnrBottomRight = 373
	case SandCnrTopLeftCnrBottomRight = 384
	case SandCnrTopRightCnrBottomRight = 400
	case SandLeftCnrTopRightCnrBottomRight = 404
	case SandCnrTopLeftCnrTopRightCnrBottomRight = 416
	case SandCnrBottomLeftCnrBottomRight = 432
	case SandTopCnrBottomLeftCnrBottomRight = 433
	case SandCnrTopLeftCnrBottomLeftCnrBottomRight = 448
	case SandCnrTopRightCnrBottomLeftCnrBottomRight = 464
	case SandCnrTopLeftCnrTopRightCnrBottomLeftCnrBottomRight = 480

public var filename: String {
	switch self {
		case .GrassTop: return "Grass_Top"
		case .GrassBottom: return "Grass_Bottom"
		case .GrassTopBottom: return "Grass_Top_Bottom"
		case .GrassLeft: return "Grass_Left"
		case .GrassTopLeft: return "Grass_Top_Left"
		case .GrassBottomLeft: return "Grass_Bottom_Left"
		case .GrassTopBottomLeft: return "Grass_Top_Bottom_Left"
		case .GrassRight: return "Grass_Right"
		case .GrassTopRight: return "Grass_Top_Right"
		case .GrassBottomRight: return "Grass_Bottom_Right"
		case .GrassTopBottomRight: return "Grass_Top_Bottom_Right"
		case .GrassLeftRight: return "Grass_Left_Right"
		case .GrassTopLeftRight: return "Grass_Top_Left_Right"
		case .GrassBottomLeftRight: return "Grass_Bottom_Left_Right"
		case .GrassTopBottomLeftRight: return "Grass_Top_Bottom_Left_Right"
		case .GrassCnrTopLeft: return "Grass_CnrTopLeft"
		case .GrassBottomCnrTopLeft: return "Grass_Bottom_CnrTopLeft"
		case .GrassRightCnrTopLeft: return "Grass_Right_CnrTopLeft"
		case .GrassBottomRightCnrTopLeft: return "Grass_Bottom_Right_CnrTopLeft"
		case .GrassCnrTopRight: return "Grass_CnrTopRight"
		case .GrassBottomCnrTopRight: return "Grass_Bottom_CnrTopRight"
		case .GrassLeftCnrTopRight: return "Grass_Left_CnrTopRight"
		case .GrassBottomLeftCnrTopRight: return "Grass_Bottom_Left_CnrTopRight"
		case .GrassCnrTopLeftCnrTopRight: return "Grass_CnrTopLeft_CnrTopRight"
		case .GrassBottomCnrTopLeftCnrTopRight: return "Grass_Bottom_CnrTopLeft_CnrTopRight"
		case .GrassCnrBottomLeft: return "Grass_CnrBottomLeft"
		case .GrassTopCnrBottomLeft: return "Grass_Top_CnrBottomLeft"
		case .GrassRightCnrBottomLeft: return "Grass_Right_CnrBottomLeft"
		case .GrassTopRightCnrBottomLeft: return "Grass_Top_Right_CnrBottomLeft"
		case .GrassCnrTopLeftCnrBottomLeft: return "Grass_CnrTopLeft_CnrBottomLeft"
		case .GrassRightCnrTopLeftCnrBottomLeft: return "Grass_Right_CnrTopLeft_CnrBottomLeft"
		case .GrassCnrTopRightCnrBottomLeft: return "Grass_CnrTopRight_CnrBottomLeft"
		case .GrassCnrTopLeftCnrTopRightCnrBottomLeft: return "Grass_CnrTopLeft_CnrTopRight_CnrBottomLeft"
		case .GrassCnrBottomRight: return "Grass_CnrBottomRight"
		case .GrassTopCnrBottomRight: return "Grass_Top_CnrBottomRight"
		case .GrassLeftCnrBottomRight: return "Grass_Left_CnrBottomRight"
		case .GrassTopLeftCnrBottomRight: return "Grass_Top_Left_CnrBottomRight"
		case .GrassCnrTopLeftCnrBottomRight: return "Grass_CnrTopLeft_CnrBottomRight"
		case .GrassCnrTopRightCnrBottomRight: return "Grass_CnrTopRight_CnrBottomRight"
		case .GrassLeftCnrTopRightCnrBottomRight: return "Grass_Left_CnrTopRight_CnrBottomRight"
		case .GrassCnrTopLeftCnrTopRightCnrBottomRight: return "Grass_CnrTopLeft_CnrTopRight_CnrBottomRight"
		case .GrassCnrBottomLeftCnrBottomRight: return "Grass_CnrBottomLeft_CnrBottomRight"
		case .GrassTopCnrBottomLeftCnrBottomRight: return "Grass_Top_CnrBottomLeft_CnrBottomRight"
		case .GrassCnrTopLeftCnrBottomLeftCnrBottomRight: return "Grass_CnrTopLeft_CnrBottomLeft_CnrBottomRight"
		case .GrassCnrTopRightCnrBottomLeftCnrBottomRight: return "Grass_CnrTopRight_CnrBottomLeft_CnrBottomRight"
		case .GrassCnrTopLeftCnrTopRightCnrBottomLeftCnrBottomRight: return "Grass_CnrTopLeft_CnrTopRight_CnrBottomLeft_CnrBottomRight"
		case .SandTop: return "Sand_Top"
		case .SandBottom: return "Sand_Bottom"
		case .SandTopBottom: return "Sand_Top_Bottom"
		case .SandLeft: return "Sand_Left"
		case .SandTopLeft: return "Sand_Top_Left"
		case .SandBottomLeft: return "Sand_Bottom_Left"
		case .SandTopBottomLeft: return "Sand_Top_Bottom_Left"
		case .SandRight: return "Sand_Right"
		case .SandTopRight: return "Sand_Top_Right"
		case .SandBottomRight: return "Sand_Bottom_Right"
		case .SandTopBottomRight: return "Sand_Top_Bottom_Right"
		case .SandLeftRight: return "Sand_Left_Right"
		case .SandTopLeftRight: return "Sand_Top_Left_Right"
		case .SandBottomLeftRight: return "Sand_Bottom_Left_Right"
		case .SandTopBottomLeftRight: return "Sand_Top_Bottom_Left_Right"
		case .SandCnrTopLeft: return "Sand_CnrTopLeft"
		case .SandBottomCnrTopLeft: return "Sand_Bottom_CnrTopLeft"
		case .SandRightCnrTopLeft: return "Sand_Right_CnrTopLeft"
		case .SandBottomRightCnrTopLeft: return "Sand_Bottom_Right_CnrTopLeft"
		case .SandCnrTopRight: return "Sand_CnrTopRight"
		case .SandBottomCnrTopRight: return "Sand_Bottom_CnrTopRight"
		case .SandLeftCnrTopRight: return "Sand_Left_CnrTopRight"
		case .SandBottomLeftCnrTopRight: return "Sand_Bottom_Left_CnrTopRight"
		case .SandCnrTopLeftCnrTopRight: return "Sand_CnrTopLeft_CnrTopRight"
		case .SandBottomCnrTopLeftCnrTopRight: return "Sand_Bottom_CnrTopLeft_CnrTopRight"
		case .SandCnrBottomLeft: return "Sand_CnrBottomLeft"
		case .SandTopCnrBottomLeft: return "Sand_Top_CnrBottomLeft"
		case .SandRightCnrBottomLeft: return "Sand_Right_CnrBottomLeft"
		case .SandTopRightCnrBottomLeft: return "Sand_Top_Right_CnrBottomLeft"
		case .SandCnrTopLeftCnrBottomLeft: return "Sand_CnrTopLeft_CnrBottomLeft"
		case .SandRightCnrTopLeftCnrBottomLeft: return "Sand_Right_CnrTopLeft_CnrBottomLeft"
		case .SandCnrTopRightCnrBottomLeft: return "Sand_CnrTopRight_CnrBottomLeft"
		case .SandCnrTopLeftCnrTopRightCnrBottomLeft: return "Sand_CnrTopLeft_CnrTopRight_CnrBottomLeft"
		case .SandCnrBottomRight: return "Sand_CnrBottomRight"
		case .SandTopCnrBottomRight: return "Sand_Top_CnrBottomRight"
		case .SandLeftCnrBottomRight: return "Sand_Left_CnrBottomRight"
		case .SandTopLeftCnrBottomRight: return "Sand_Top_Left_CnrBottomRight"
		case .SandCnrTopLeftCnrBottomRight: return "Sand_CnrTopLeft_CnrBottomRight"
		case .SandCnrTopRightCnrBottomRight: return "Sand_CnrTopRight_CnrBottomRight"
		case .SandLeftCnrTopRightCnrBottomRight: return "Sand_Left_CnrTopRight_CnrBottomRight"
		case .SandCnrTopLeftCnrTopRightCnrBottomRight: return "Sand_CnrTopLeft_CnrTopRight_CnrBottomRight"
		case .SandCnrBottomLeftCnrBottomRight: return "Sand_CnrBottomLeft_CnrBottomRight"
		case .SandTopCnrBottomLeftCnrBottomRight: return "Sand_Top_CnrBottomLeft_CnrBottomRight"
		case .SandCnrTopLeftCnrBottomLeftCnrBottomRight: return "Sand_CnrTopLeft_CnrBottomLeft_CnrBottomRight"
		case .SandCnrTopRightCnrBottomLeftCnrBottomRight: return "Sand_CnrTopRight_CnrBottomLeft_CnrBottomRight"
		case .SandCnrTopLeftCnrTopRightCnrBottomLeftCnrBottomRight: return "Sand_CnrTopLeft_CnrTopRight_CnrBottomLeft_CnrBottomRight"
	}
}

}
